[project]
name = "octoopt"
version = "0.1.0"
description = "octo automation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.2.1",
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
]


[tool.ruff]
line-length = 88
